module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        // Core areas
        'core',
        'api',
        'ui',
        'offline',
        'auth',
        'docs',
        'ci',
        'deps',
        // Project areas
        'frontend',
        'backend',
        'tests',
        'seeding',
        // Feature modules
        'eeg',
        'exercises',
        'injects',
        'msel',
        'observations',
        'organizations',
        'clock',
        'conduct',
        'metrics',
        'settings',
        'reports',
        'version',
        'capabilities',
        'approval',
        'inject-approval',
        'email',
        'email-communications',
        'invitation',
        'bulk-participant-import',
        'feature-flags',
        'system-settings',
        'hseep-roles',
        'field-operations',
        'photo-capture',
        'photos',
        'delivery-methods',
        // Infrastructure
        'agent',
        'migrations',
        'db',
        'signalr',
        'pwa',
        'telemetry',
        'database',
        'logging',
        'infra',
      ],
    ],
    'scope-empty': [1, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'infra',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
  },
};
