// <auto-generated />
using System;
using Cadence.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cadence.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cadence.Core.Models.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveMselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPracticeMode")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActiveMselId");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.ExerciseParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ExerciseId", "UserId")
                        .IsUnique();

                    b.ToTable("ExerciseParticipants");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.HseepRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanFireInjects")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageExercise")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRecordObservations")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemWide")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HseepRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanFireInjects = true,
                            CanManageExercise = true,
                            CanRecordObservations = true,
                            Code = "Administrator",
                            Description = "System-wide configuration and user management. Has full access to all exercises within their organization.",
                            IsActive = true,
                            IsSystemWide = true,
                            Name = "Administrator",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CanFireInjects = true,
                            CanManageExercise = true,
                            CanRecordObservations = true,
                            Code = "ExerciseDirector",
                            Description = "Full exercise management authority. Responsible for Go/No-Go decisions and overall exercise conduct.",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Exercise Director",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CanFireInjects = true,
                            CanManageExercise = false,
                            CanRecordObservations = false,
                            Code = "Controller",
                            Description = "Delivers injects to players and manages scenario flow during exercise conduct.",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Controller",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CanFireInjects = false,
                            CanManageExercise = false,
                            CanRecordObservations = true,
                            Code = "Evaluator",
                            Description = "Observes and documents player performance for the After-Action Report (AAR).",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Evaluator",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CanFireInjects = false,
                            CanManageExercise = false,
                            CanRecordObservations = false,
                            Code = "Observer",
                            Description = "Watches exercise conduct without interfering. Read-only access to exercise data.",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Observer",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Inject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ControllerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExpectedAction")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FireCondition")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FiredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FiredBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InjectNumber")
                        .HasColumnType("int");

                    b.Property<string>("InjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentInjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScenarioDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ScenarioTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SkippedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FiredBy");

                    b.HasIndex("ParentInjectId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("SkippedBy");

                    b.HasIndex("MselId", "InjectNumber")
                        .IsUnique();

                    b.HasIndex("MselId", "Sequence");

                    b.HasIndex("MselId", "Status");

                    b.ToTable("Injects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Msel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "Version");

                    b.ToTable("Msels");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ObjectiveNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "ObjectiveNumber");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "Sequence");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Exercise", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Msel", "ActiveMsel")
                        .WithMany()
                        .HasForeignKey("ActiveMselId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Organization", "Organization")
                        .WithMany("Exercises")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActiveMsel");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.ExerciseParticipant", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Participants")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cadence.Core.Models.Entities.User", "User")
                        .WithMany("ExerciseParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Inject", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.User", "FiredByUser")
                        .WithMany()
                        .HasForeignKey("FiredBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Msel", "Msel")
                        .WithMany("Injects")
                        .HasForeignKey("MselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cadence.Core.Models.Entities.Inject", "ParentInject")
                        .WithMany("ChildInjects")
                        .HasForeignKey("ParentInjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Phase", "Phase")
                        .WithMany("Injects")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.User", "SkippedByUser")
                        .WithMany()
                        .HasForeignKey("SkippedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FiredByUser");

                    b.Navigation("Msel");

                    b.Navigation("ParentInject");

                    b.Navigation("Phase");

                    b.Navigation("SkippedByUser");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Msel", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Msels")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Objective", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Objectives")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Phase", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Phases")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.User", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Exercise", b =>
                {
                    b.Navigation("Msels");

                    b.Navigation("Objectives");

                    b.Navigation("Participants");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Inject", b =>
                {
                    b.Navigation("ChildInjects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Msel", b =>
                {
                    b.Navigation("Injects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Organization", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Phase", b =>
                {
                    b.Navigation("Injects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.User", b =>
                {
                    b.Navigation("ExerciseParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
