// <auto-generated />
using System;
using Cadence.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cadence.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cadence.Core.Models.Entities.DeliveryMethodLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOther")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("DeliveryMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Spoken directly to player",
                            IsActive = true,
                            IsDeleted = false,
                            IsOther = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Verbal",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Simulated phone call",
                            IsActive = true,
                            IsDeleted = false,
                            IsOther = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Phone",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Simulated email",
                            IsActive = true,
                            IsDeleted = false,
                            IsOther = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Email",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Radio communication",
                            IsActive = true,
                            IsDeleted = false,
                            IsOther = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Radio",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Paper document",
                            IsActive = true,
                            IsDeleted = false,
                            IsOther = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Written",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "CAX/simulation input",
                            IsActive = true,
                            IsDeleted = false,
                            IsOther = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Simulation",
                            SortOrder = 6,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Custom delivery method (specify in notes)",
                            IsActive = true,
                            IsDeleted = false,
                            IsOther = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Other",
                            SortOrder = 99,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActivatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveMselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("ClockElapsedBeforePause")
                        .HasColumnType("time");

                    b.Property<DateTime?>("ClockStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClockStartedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClockState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasBeenPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPracticeMode")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TimeScale")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimelineMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedBy");

                    b.HasIndex("ActiveMselId");

                    b.HasIndex("ArchivedBy");

                    b.HasIndex("ClockStartedBy");

                    b.HasIndex("CompletedBy");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.ExerciseParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ExerciseId", "UserId")
                        .IsUnique();

                    b.ToTable("ExerciseParticipants");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.ExpectedOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EvaluatorNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("InjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("WasAchieved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InjectId", "SortOrder");

                    b.ToTable("ExpectedOutcomes");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.HseepRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanFireInjects")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageExercise")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRecordObservations")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemWide")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HseepRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanFireInjects = true,
                            CanManageExercise = true,
                            CanRecordObservations = true,
                            Code = "Administrator",
                            Description = "System-wide configuration and user management. Has full access to all exercises within their organization.",
                            IsActive = true,
                            IsSystemWide = true,
                            Name = "Administrator",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CanFireInjects = true,
                            CanManageExercise = true,
                            CanRecordObservations = true,
                            Code = "ExerciseDirector",
                            Description = "Full exercise management authority. Responsible for Go/No-Go decisions and overall exercise conduct.",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Exercise Director",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CanFireInjects = true,
                            CanManageExercise = false,
                            CanRecordObservations = false,
                            Code = "Controller",
                            Description = "Delivers injects to players and manages scenario flow during exercise conduct.",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Controller",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CanFireInjects = false,
                            CanManageExercise = false,
                            CanRecordObservations = true,
                            Code = "Evaluator",
                            Description = "Observes and documents player performance for the After-Action Report (AAR).",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Evaluator",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CanFireInjects = false,
                            CanManageExercise = false,
                            CanRecordObservations = false,
                            Code = "Observer",
                            Description = "Watches exercise conduct without interfering. Read-only access to exercise data.",
                            IsActive = true,
                            IsSystemWide = false,
                            Name = "Observer",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Inject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ControllerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("DeliveryMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryMethodOther")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan?>("DeliveryTime")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExpectedAction")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FireCondition")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FiredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FiredBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InjectNumber")
                        .HasColumnType("int");

                    b.Property<string>("InjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentInjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponsibleController")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ScenarioDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ScenarioTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SkippedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Track")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("FiredBy");

                    b.HasIndex("ParentInjectId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("SkippedBy");

                    b.HasIndex("Track");

                    b.HasIndex("MselId", "InjectNumber")
                        .IsUnique();

                    b.HasIndex("MselId", "Sequence");

                    b.HasIndex("MselId", "Status");

                    b.ToTable("Injects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.InjectObjective", b =>
                {
                    b.Property<Guid>("InjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InjectId", "ObjectiveId");

                    b.HasIndex("InjectId");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("InjectObjectives");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Msel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "Version");

                    b.ToTable("Msels");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ObjectiveNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "ObjectiveNumber");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ObjectiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rating")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("InjectId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("ObservedAt");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Default organization for the Cadence system",
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Default Organization",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId", "Sequence");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "System",
                            Email = "system@cadence.local",
                            IsDeleted = false,
                            IsSystemAdmin = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            OrganizationId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Exercise", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.User", "ActivatedByUser")
                        .WithMany()
                        .HasForeignKey("ActivatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Msel", "ActiveMsel")
                        .WithMany()
                        .HasForeignKey("ActiveMselId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.User", "ArchivedByUser")
                        .WithMany()
                        .HasForeignKey("ArchivedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.User", "ClockStartedByUser")
                        .WithMany()
                        .HasForeignKey("ClockStartedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Organization", "Organization")
                        .WithMany("Exercises")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivatedByUser");

                    b.Navigation("ActiveMsel");

                    b.Navigation("ArchivedByUser");

                    b.Navigation("ClockStartedByUser");

                    b.Navigation("CompletedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.ExerciseParticipant", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Participants")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cadence.Core.Models.Entities.User", "User")
                        .WithMany("ExerciseParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.ExpectedOutcome", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Inject", "Inject")
                        .WithMany("ExpectedOutcomes")
                        .HasForeignKey("InjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inject");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Inject", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.DeliveryMethodLookup", "DeliveryMethodLookup")
                        .WithMany("Injects")
                        .HasForeignKey("DeliveryMethodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.User", "FiredByUser")
                        .WithMany()
                        .HasForeignKey("FiredBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Msel", "Msel")
                        .WithMany("Injects")
                        .HasForeignKey("MselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cadence.Core.Models.Entities.Inject", "ParentInject")
                        .WithMany("ChildInjects")
                        .HasForeignKey("ParentInjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Phase", "Phase")
                        .WithMany("Injects")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.User", "SkippedByUser")
                        .WithMany()
                        .HasForeignKey("SkippedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DeliveryMethodLookup");

                    b.Navigation("FiredByUser");

                    b.Navigation("Msel");

                    b.Navigation("ParentInject");

                    b.Navigation("Phase");

                    b.Navigation("SkippedByUser");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.InjectObjective", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Inject", "Inject")
                        .WithMany("InjectObjectives")
                        .HasForeignKey("InjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cadence.Core.Models.Entities.Objective", "Objective")
                        .WithMany("InjectObjectives")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Inject");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Msel", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Msels")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Objective", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Objectives")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Observation", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Observations")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cadence.Core.Models.Entities.Inject", "Inject")
                        .WithMany("Observations")
                        .HasForeignKey("InjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cadence.Core.Models.Entities.Objective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Exercise");

                    b.Navigation("Inject");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Phase", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Exercise", "Exercise")
                        .WithMany("Phases")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.User", b =>
                {
                    b.HasOne("Cadence.Core.Models.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.DeliveryMethodLookup", b =>
                {
                    b.Navigation("Injects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Exercise", b =>
                {
                    b.Navigation("Msels");

                    b.Navigation("Objectives");

                    b.Navigation("Observations");

                    b.Navigation("Participants");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Inject", b =>
                {
                    b.Navigation("ChildInjects");

                    b.Navigation("ExpectedOutcomes");

                    b.Navigation("InjectObjectives");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Msel", b =>
                {
                    b.Navigation("Injects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Objective", b =>
                {
                    b.Navigation("InjectObjectives");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Organization", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.Phase", b =>
                {
                    b.Navigation("Injects");
                });

            modelBuilder.Entity("Cadence.Core.Models.Entities.User", b =>
                {
                    b.Navigation("ExerciseParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
